### ISSUE TITLE
Get crushed with error message  setObjectForKey: object cannot be nil (key: downloadTask)

### ISSUE THREAD

**Issue by avaiyakirtib** [mzeeshanid/MZDownloadManager#10]
I am using this class for downloading of more than 100 PDFs at a time by using addtask delegate method of MZDownloadManager , But after 2-3 times of exceution its getting below error and my app goes to be crushed 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: downloadTask)'

and for low number of PDFs its working fine , can you please suggest the solution ?
I hav tried with dispatch_queus but its not working

**Comment by mzeeshanid** [comment]
Fixed.
