### ISSUE TITLE
Invalid URL scheme for background downloads: (null). Valid schemes are http or https

### ISSUE THREAD

**Issue by gasparenovara** [mzeeshanid/MZDownloadManager#11]
When call
- (void)addDownloadTask:(NSString *)fileName fileURL:(NSString *)fileURL

if fileURL contain white space in filename so

we have: Invalid URL scheme for background downloads: (null). Valid schemes are http or https

Please replace this line

NSURL *url = [NSURL URLWithString:fileURL];

whith:

NSURL *url = [NSURL URLWithString:
                  [[fileURL stringByAddingPercentEscapesUsingEncoding: NSUTF8StringEncoding]
                   stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]];

**Comment by mzeeshanid** [comment]
Obviously you can pass the correct the url before sending it to the download manager.

**Comment by spmPrem** [comment]
Nice its working Fine with 
NSURL *url = [NSURL URLWithString:
[[fileURL stringByAddingPercentEscapesUsingEncoding: NSUTF8StringEncoding]
stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]];
