### ISSUE TITLE
App rejected by Apple when using this component and copying to documents directory

### ISSUE THREAD

**Issue by nikhilcoolstuff** [mzeeshanid/MZDownloadManager#13]
If we use this control to download files, and save to document directory, Apple rejects it because the downloaded data is by default synced to iCloud. 

Please add the below code in addDownloadTask method to set NSURLIsExcludedFromBackupKey so files are not automatically synced to iCloud and Apple accepts it :). 

- (void)addDownloadTask:(NSString *)fileName fileURL:(NSString *)fileURL
{
    NSURL *url = [NSURL URLWithString:fileURL];
    [url setResourceValue:@(YES) forKey:NSURLIsExcludedFromBackupKey error:nil];
...
...

**Comment by mythodeia** [comment]
i think this is outside the scope of the library. This library does what its supposed to do well. Personally i think its the user's responsibility to set whatever permissions he wants. But thats just my opinion :+1:

**Comment by mzeeshanid** [comment]
Yes @mythodeia  you are right. 
@nikhilcoolstuff Let say if i add that flag to prevent iCloud sync within the library then you download a document file and you want it to be synced to iCloud.
Thats why you have to decide yourself which file can be synced or which one can't be.
Thanks
