### ISSUE TITLE
timeoutIntervalForRequest does not work

### ISSUE THREAD

**Issue by dodosp** [mzeeshanid/MZDownloadManager#14]
I have set timeoutIntervalForRequest in the session configuration and tried with a URL that gives a timeout "http://www.google.com:81/" but the timeout is not triggered, didFinishWithError is not called. On the contrary if i ser timeoutIntervalForResponse this timeout is triggered. Maybe you have some insight?

**Comment by mzeeshanid** [comment]
In general, an NSURLSession background session does not fail a task if something goes wrong on the wire. Rather, it continues looking for a good time to run the request and retries at that time. This continues until the resource timeout expires (that is, the value of the timeoutIntervalForResource property in the NSURLSessionConfiguration object you use to create the session). The current default for that value is one week!

[For more details](http://stackoverflow.com/questions/23288780/nsurlsessiontask-never-calls-back-after-timeout-when-using-background-configurat)
