### ISSUE TITLE
This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.

### ISSUE THREAD

**Issue by hilalbaig** [mzeeshanid/MZDownloadManager#17]
iOS 9 shows this error while downloading a file..
[MZDownloadManagerViewController URLSession:downloadTask:didFinishDownloadingToURL:]

**Comment by mzeeshanid** [comment]
Added Transport security settings for iOS 9 now closing this issue
