### ISSUE TITLE
Invalid URL scheme for background downloads: ftp. Valid schemes are http or https

### ISSUE THREAD

**Issue by zeqinjie** [mzeeshanid/MZDownloadManager#18]
When I try to use FTP transmission mode，the  issues is  "Invalid URL scheme for background downloads: ftp. Valid schemes are http or https"

**Comment by mzeeshanid** [comment]
This component is designed to work with http.

**Comment by zeqinjie** [comment]
thank ,but when i chang the NSURLSessionConfiguration  to  defaultSessionConfiguration,it can downloads,just  it  can not suport the background downloads,how to solve ？

**Comment by ruchiragile** [comment]
Same issue found. How to solve for "https"?
