### ISSUE TITLE
How to change 'baseFilePath' or 'destinationPath' of the download file

### ISSUE THREAD

**Issue by l900416** [mzeeshanid/MZDownloadManager#22]
A very great job!
Can I change the  'baseFilePath' or 'destinationPath' of the download file with pod 'MZDownloadManager'

Thanks！

**Comment by mzeeshanid** [comment]
Currently to change baseFilePath you have to change it in the pods. 
It looks like it must has an option to change. I am adding this feature in up coming update.

**Comment by mzeeshanid** [comment]
I have pushed some changes on a separate branch. Could you please test it and verify all is ok and this is exactly what you need?

**Comment by l900416** [comment]
Nice. That's exactly what I need. 
Thanks for your reply

**Comment by mzeeshanid** [comment]
Ok thanks I will now merge it with the master branch.

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 1, 2016 at 5:56 AM, liangtong<notifications@github.com> wrote:   
Nice. That's exactly what I need. 
Thanks for your reply
