### ISSUE TITLE
Swift 3.0 errors

### ISSUE THREAD

**Issue by JaleelNazir** [mzeeshanid/MZDownloadManager#23]
Can you release Swift 3.0 ver?

**Comment by mzeeshanid** [comment]
I have updated it for swift 3.0
Now I will update the cocoapods version.

**Comment by kostapappas** [comment]
seems cocoapod not yet updated. You can use 
 pod "MZDownloadManager", :git => 'https://github.com/mzeeshanid/MZDownloadManager.git'

to get the latest build

**Comment by mzeeshanid** [comment]
Podspec is updated so closing now.

**Comment by jlubeck** [comment]
It doesn't seem to be updated, as installing with Cocoapods is still installing 3.1 as the latest.
