### ISSUE TITLE
kill app and resume download

### ISSUE THREAD

**Issue by andreabozza1984** [mzeeshanid/MZDownloadManager#24]
Hello,
i have this scenario (in example app):
- close the application by tapping home button and swipe out the application
- reopen application
- i see this scenario:
![img_1518](https://cloud.githubusercontent.com/assets/18351962/19190425/b9c05294-8c9d-11e6-9dd5-49469e140b34.PNG)
There is a way to avoid this?
thank you 
Andrea

**Comment by mzeeshanid** [comment]
Are you testing in a real device or in simulator?

Sent from Yahoo Mail on Android 
 
  On Fri, Oct 7, 2016 at 5:53 PM, andreabozza1984<notifications@github.com> wrote:   
Hello,
i have this scenario (in example app):
   
   - close the application by tapping home button and swipe out the application
   - reopen application
   - i see this scenario:There is a way to avoid this?thank you Andrea

**Comment by andreabozza1984** [comment]
device.  ios 1.0.2 on iPhone 6 plus

**Comment by vishnuag05** [comment]
same is happening with me , I am testing in real device.Please reply asap. @mzeeshanid

**Comment by mzeeshanid** [comment]
When user force quit the app, all on going tasks are invalidated by the Daemon. So if you want to start them without user interaction you have to traverse tasks array and resume it programmatically. This is not a bug, its expected behaviour.

**Comment by iMuks** [comment]
This is as per apple iOS nsurlsession background session configuration default.when user kill app while app is running in foreground then nsurlsession or os will kill the task .and when user launch app again, then nsurl background session invoke and resume the download task.
