### ISSUE TITLE
Project Not Building

### ISSUE THREAD

**Issue by professionalsna** [mzeeshanid/MZDownloadManager#26]
Hi, Zeeshan

you did a great work, when i used your sample project it worked for me, but when i install it from cocoapods into my project it shows 79 issues on build time see the following issue

http://imgur.com/a/SuhAd

regards,
Naveed

**Comment by mzeeshanid** [comment]
Are you using swift 3.0?

**Comment by kostapappas** [comment]
same here

**Comment by kostapappas** [comment]
@professionalsna 
use  pod "MZDownloadManager", :git => 'https://github.com/mzeeshanid/MZDownloadManager.git'

**Comment by mzeeshanid** [comment]
Thanks @kostapappas  
I will update the pod version. For now you can fetch as mentioned above.

**Comment by professionalsna** [comment]
Thanks  @kostapappas 
will check..

**Comment by mzeeshanid** [comment]
Podspec is updated so closing now.
