### ISSUE TITLE
How to get the name of downloaded file(eg.:suggestedFilename)

### ISSUE THREAD

**Issue by leogeng** [mzeeshanid/MZDownloadManager#27]
I download a file by a temp URL and no filename.

I note that  user can get filename when dowload file with URLSession:
- (NSURLSessionDownloadTask *)downloadTaskWithRequest:(NSURLRequest *)request completionHandler:(void (^)(NSURL * _Nullable location, NSURLResponse * _Nullable response, NSError * _Nullable error))completionHandler;

There is a property named 'suggestedFilename'.

Can i get something as suggestedFilename in MZDownloadManager?

**Comment by mzeeshanid** [comment]
Currently MZDownloadManager does not provide support for 'suggestedFilename'. But obviously you can modify the source code to achieve this behaviour.
