### ISSUE TITLE
Dropped support for iOS 8?

### ISSUE THREAD

**Issue by jlubeck** [mzeeshanid/MZDownloadManager#39]
I noticed on your commit on November that your changed support from iOS 8 to iOS 9.

Can you share why or what would need to be done on a fork to continue supporting iOS 8? unfortunately I was using this on an enterprise app and they need to continue supporting iOS 8 who know why...

Thank you

**Comment by mzeeshanid** [comment]
There is nothing special for iOS 9. It can be easily ported to iOS 8.
Try by setting the minimum deployment target to iOS 8.

**Comment by jlubeck** [comment]
I'm sorry @mzeeshanid, forgot to mention that just by changing the target to 8 worked. Makes me wonder why you changed it though?
