### ISSUE TITLE
OC version

### ISSUE THREAD

**Issue by wwwang89** [mzeeshanid/MZDownloadManager#46]
is there any OC version for  MZDownloadManager ？thx

**Comment by mzeeshanid** [comment]
By the way it is originally developed in objective-c and I updated it with swift. Currently i don't have any maintained objective-c version
Why you need it in Objective-C ? Is there any specific reason?

**Comment by wwwang89** [comment]
ahh， got it，I just not familiar with Swift。thank  you all the same，I'll learn Swift after now 😄
