### ISSUE TITLE
How to remove items from MZDownloadManager's downloadingArray?

### ISSUE THREAD

**Issue by xtreme8210** [mzeeshanid/MZDownloadManager#57]
I have run "cancelTaskAtIndex:", but this does not remove the mzdownloadModel in the MZDownloadManager's downloadingArray.

Please help. thank you

**Comment by Amirhasanioox** [comment]
You can use that :
self.downloadManager.cancelTaskAtIndex(indexPath.row)

**Comment by xtreme8210** [comment]
Hi, I have tried
`[self.downloadManager cancelTaskAtIndex:selectedIndexPath.row];`
then reload datas
`[self.downloadingArray removeAllObjects];
    self.downloadingArray = [[NSMutableArray alloc] initWithArray:(NSMutableArray *)self.downloadManager.downloadingArray];`

I still get the data that I just deleted. Please help.

**Comment by xtreme8210** [comment]
I found out, I should reload data in the delegate
`- (void)downloadRequestCanceled:(MZDownloadModel *)downloadModel index:(NSInteger)index;`
