### ISSUE TITLE
help , Initialize MZDownloadManagerViewController 

### ISSUE THREAD

**Issue by syrakozz** [mzeeshanid/MZDownloadManager#6]
how can i Initialize MZDownloadManagerViewController 
im not using tabbar
i try 
  UINavigationController *mzDownloadingNav = [self.navigationController.viewControllers objectAtIndex: [self.navigationController.viewControllers count]-1];

    mzDownloadingViewObj = [mzDownloadingNav.viewControllers objectAtIndex:0] ;

but it didnt work

**Comment by mzeeshanid** [comment]
New convenient methods are available for initialisation.
