### ISSUE TITLE
Can not download file

### ISSUE THREAD

**Issue by bhavin-chauhan** [mzeeshanid/MZDownloadManager#63]
Hi, 
First of all thanks for great library.
I've download code and clone same project. But somehow downloading task in not working. I think I missed some point but couldn't figure out issue. I've installed pod file and project compile & run successfully. But after request for download file, file size are not calculating and couldn't be download. Could you please help me to figure out this issue? I've uploaded that sample code [here](https://github.com/bhavin-chauhan/SampleDownload)  [issue is](https://screencast.com/t/HAopf5aFJO). Please give me any suggestions.

**Comment by ambujshukla** [comment]
Hi Bhavin,
   Did you find the solution as I am also getting this issue.

**Comment by Z--EN** [comment]
seems here solution: https://github.com/mzeeshanid/MZDownloadManager/pull/64/files

**Comment by mzeeshanid** [comment]
Fixed in latest version
