### ISSUE TITLE
Download failed message / delegate?

### ISSUE THREAD

**Issue by sambudda** [mzeeshanid/MZDownloadManager#7]
I wanted to check and see if for some reason download failed or if the link was bad to begin with, how can I catch that and tell the user that file cannot be downloaded.

for example in the files I changed the first file path to http://dl.dropbox.com/u/97700329/100_file1.mp4
When I click on the download I get no errors. How can I add an error message? I did not see any failure delegate method.

**Comment by mzeeshanid** [comment]
Failure  delegate is added in new version.
