### ISSUE TITLE
Why I force quit APP, the resume download from zero

### ISSUE THREAD

**Issue by saminlu** [mzeeshanid/MZDownloadManager#72]
Why I force quit APP, the resume download from zero.
But your demo can resume part of them, doesn't start from zero.
What is the key point to fix the bug?

**Comment by mahadshahib** [comment]
how do you fix thiss?

**Comment by bhavin-chauhan** [comment]
saminlu Can you please explain me how you solved this issue. I am facing same issue.

**Comment by Y2JChamp** [comment]
saminlu, how did u fix the issue?
