### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by prabhatranjan143** [mzeeshanid/MZDownloadManager#83]
When I am downloading files it's producing SSL error.
"Error while downloading file: Optional(\"image001.jpg\")  Error: Error Domain=NSURLErrorDomain Code=-1200 \"An SSL error has occurred and a secure connection to the server cannot be made.\" UserInfo={NSErrorClientCertificateStateKey=0, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundDownloadTask <D2A42941-33B1-4EC6-BBA8-8D83AFC3941B>.<1>, NSErrorFailingURLKey=https://indefend.net:8443/service/home/~/?id=268&part=2&auth=co&disp=a, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"BackgroundDownloadTask <D2A42941-33B1-4EC6-BBA8-8D83AFC3941B>.<1>\",\n    \"LocalDownloadTask <D2A42941-33B1-4EC6-BBA8-8D83AFC3941B>.<1>\"\n), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLStringKey=https://indefend.net:8443/service/home/~/?id=268&part=2&auth=co&disp=a, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802}"

Could you please help me to figure out how to resolve this issue.

**Comment by mzeeshanid** [comment]
This issue is not related to MZDownloadManager. I have tested downloading with HTTPS from dropbox and other file sharing sites. It is working fine. Please verify your SSL certificate.

**Comment by mzeeshanid** [comment]
Moreover the link in the message above is not working.
