### ISSUE TITLE
Issue on MZDownloadManager.swift isValidResumeData line 156

### ISSUE THREAD

**Issue by 7snalbar** [mzeeshanid/MZDownloadManager#85]
The reason for the crash or the scenario that this crash is caused is not clear for now. I will be attaching the crash report from Firebase Crashlytics and let's hope someone faced the same issue and may provide either a scenario for this crash to be triggered so I can debug it and the have a solution for it. 
<img width="1138" alt="screen shot 2019-03-05 at 14 15 28" src="https://user-images.githubusercontent.com/24737691/53801845-4db32e00-3f51-11e9-8b9a-d486c2b6c327.png">

**Comment by Harshad290194** [comment]
@7snalbar also repeat same issue for resume downloading

**Comment by 7snalbar** [comment]
@Harshad290194 Did you understand what caused it? Or do you have any more information on how to regenerate the issue? If yes then It'd help me solve it. Since @mzeeshanid doesn't care to reply on the issues that his work caused. 

Thanks

**Comment by Harshad290194** [comment]
@7snalbar When we pause download task and resume again then crassh issue is generated.. not for every time but some time generate... issue is generated in latest pod file... not old pod file...

**Comment by Harshad290194** [comment]
@7snalbar When we start downloading and kill app when already downloading inProgress.. and resume download then crash is generated... for resume data...

**Comment by CokePokes** [comment]
This this: 

`fileprivate func isValidResumeData(_ resumeData: Data?) -> Bool {
        
        guard resumeData != nil || resumeData?.count > 0 else {
            return false
        }
        
        do {
            var resumeDictionary : AnyObject!
            resumeDictionary = try PropertyListSerialization.propertyList(from: resumeData!, options: PropertyListSerialization.MutabilityOptions(), format: nil) as AnyObject?
            var localFilePath = (resumeDictionary?["NSURLSessionResumeInfoLocalPath"] as? String)
            
            if localFilePath == nil || localFilePath?.count < 1 {
                localFilePath = (NSTemporaryDirectory() as String) + (resumeDictionary["NSURLSessionResumeInfoTempFileName"] as! String)
            }
            
            let fileManager : FileManager! = FileManager.default
            debugPrint("resume data file exists: \(fileManager.fileExists(atPath: localFilePath! as String))")
            return fileManager.fileExists(atPath: localFilePath! as String)
        } catch let error as NSError {
            debugPrint("resume data is nil: \(error)")
            return false
        }
    }`

**Comment by shubhankarbhavsar** [comment]
Hi All,

I'm also facing this issue. Anyone working on solutions?

**Comment by mml237** [comment]
Hello everyone!
I'am also facing this issue. When I pause the task, relaunch the app and click the Downloading button. The crash occur.
![image](https://user-images.githubusercontent.com/22297921/60286520-4372d080-9942-11e9-97ed-5051fc50055e.png)
![image](https://user-images.githubusercontent.com/22297921/60286563-5f767200-9942-11e9-8e45-c17768f82fc1.png)
![image](https://user-images.githubusercontent.com/22297921/60286628-83d24e80-9942-11e9-8711-dcc143507825.png)
![image](https://user-images.githubusercontent.com/22297921/60286700-a2384a00-9942-11e9-8359-51a32649496a.png)
Anyone can help me? Thanks a lot!

**Comment by mzeeshanid** [comment]
In upcoming version i will remove this function as it is no longer needed.

**Comment by dlpigpen** [comment]
> Try this:
> 
> ```
> fileprivate func isValidResumeData(_ resumeData: Data?) -> Bool {
>         
>         guard resumeData != nil || resumeData?.count > 0 else {
>             return false
>         }
>         
>         do {
>             var resumeDictionary : AnyObject!
>             resumeDictionary = try PropertyListSerialization.propertyList(from: resumeData!, options: PropertyListSerialization.MutabilityOptions(), format: nil) as AnyObject?
>             var localFilePath = (resumeDictionary?["NSURLSessionResumeInfoLocalPath"] as? String)
>             
>             if localFilePath == nil || localFilePath?.count < 1 {
>                 localFilePath = (NSTemporaryDirectory() as String) + (resumeDictionary["NSURLSessionResumeInfoTempFileName"] as! String)
>             }
>             
>             let fileManager : FileManager! = FileManager.default
>             debugPrint("resume data file exists: \(fileManager.fileExists(atPath: localFilePath! as String))")
>             return fileManager.fileExists(atPath: localFilePath! as String)
>         } catch let error as NSError {
>             debugPrint("resume data is nil: \(error)")
>             return false
>         }
>     }
> ```
> 
> Although, when resuming the download after quitting the app, the download fails and causes new downloads to fail as well. Reply if you find a fix to this issue.

Someone can let me know. Does it work?

**Comment by Harshad290194** [comment]
We already solve this issue.. Thank you so much for your reply

**Comment by dlpigpen** [comment]
@Harshad290194  Thank a lot.
